# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelegramDownloaderGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TgInterface(object):
    def setupUi(self, TgInterface):
        TgInterface.setObjectName("TgInterface")
        TgInterface.resize(500, 200)
        TgInterface.setMinimumSize(QtCore.QSize(500, 200))
        TgInterface.setMaximumSize(QtCore.QSize(500, 200))
        self.centralwidget = QtWidgets.QWidget(TgInterface)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 50, 441, 69))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.FileLine = QtWidgets.QLineEdit(self.widget)
        self.FileLine.setObjectName("FileLine")
        self.horizontalLayout.addWidget(self.FileLine)
        self.PathButton = QtWidgets.QPushButton(self.widget)
        self.PathButton.setObjectName("PathButton")
        self.horizontalLayout.addWidget(self.PathButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.urlLine = QtWidgets.QLineEdit(self.widget)
        self.urlLine.setObjectName("urlLine")
        self.horizontalLayout_2.addWidget(self.urlLine)
        self.DownloadButton = QtWidgets.QPushButton(self.widget)
        self.DownloadButton.setObjectName("DownloadButton")
        self.horizontalLayout_2.addWidget(self.DownloadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        TgInterface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TgInterface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        TgInterface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TgInterface)
        self.statusbar.setObjectName("statusbar")
        TgInterface.setStatusBar(self.statusbar)

        self.retranslateUi(TgInterface)
        QtCore.QMetaObject.connectSlotsByName(TgInterface)

    def retranslateUi(self, TgInterface):
        _translate = QtCore.QCoreApplication.translate
        TgInterface.setWindowTitle(_translate("TgInterface", "TelegraphDownloader"))
        self.label_2.setText(_translate("TgInterface", "目标位置"))
        self.PathButton.setText(_translate("TgInterface", "选择"))
        self.label.setText(_translate("TgInterface", "下载链接"))
        self.DownloadButton.setText(_translate("TgInterface", "下载"))
